---
title: Environmental Data Analysis & Simulation
year: 2025
semester: Spring
coursenumber: BEE 4850/5850
---

- **Semester:** {{< meta semester >}} {{< meta year >}}
- **Course Number:** {{< meta coursenumber >}}

## Course Description

Simulations from numerical and statistical models are a key tool used to quantify and represent our understanding of many different environmental systems, including but not limited to the climate, sea levels, air pollution, and the electric power system. Data analysis of environmental observations and model simulations is an integral part of developing and evaluating models used to 1) test our assumptions about environmental system dynamics; 2) develop new insights into environmental processes; and 3) project future environmental conditions and outcomes. This course will provide an overview of the use of generative probability models to understand data and examine hypotheses about data-generating processes. The goal is to provide students with a framework and an initial toolkit of methods for data analysis and simulation. Students will actively analyze and use real data from a variety of environmental systems. In particular, over the course of the semester, we will:

* conduct exploratory analyses of environmental datasets;
* discuss best practices for and complexities of data visualization;
* calibrate statistical and process-based numerical models using environmental data;
* use simulations from calibrated models to identify key sources of uncertainty and model error;
* assess model fit and adequacy through predictive ability.

## More Information

- This course uses the [Julia programming language](https://julialang.org).
- See the [course website](https://bee4850.viveks.me/) and [GitHub repository](https://github.com/BEE4850/bee4850.github.io).