---
title: "Heterogeneous vulnerability of zero-carbon power grids under climate-technological changes"
date: 2025-01-01
author: 
  - name: M. Vivienne Liu
    orcid: 0000-0002-5676-8591
  - name: Vivek Srikrishnan
    orcid: 0000-0003-0049-3805
    url: https://viveks.me
  - name: Elnaz Kabir
    orcid: 0000-0002-1819-9949
  - name: Scott Steinschneider
    orcid: 0000-0002-8882-1908
    url: https://blogs.cornell.edu/steinschneider/
  - name: C. Lindsay Anderson
    orcid: 0000-0002-5148-0118
    url: https://andersonenergylab-cornell.github.io/
categories:
    - electric power systems
    - power grid reliability
    - climate variability
url_source: 
url_preprint: https://arxiv.org/abs/2307.15079
url_repo: https://github.com/AndersonEnergyLab-Cornell/ny-clcpa2050
journ: "Under Review"
year: 2025
---

## Links

* [Preprint](https://arxiv.org/abs/2307.15079)
* [Code Repository](https://github.com/AndersonEnergyLab-Cornell/ny-clcpa2050)

## Abstract

The transition to decarbonized energy systems has become a priority globally to mitigate carbon emissions and, therefore, climate change. However, the vulnerabilities of zero-carbon power grids under climatic and technological changes have not been thoroughly examined. In this study, we focus on modeling the zero-carbon grid using a dataset that captures diverse future climatic-technological scenarios, with New York State as a case study. By accurately representing the topology and operational constraints of the power grid, we identify spatiotemporal heterogeneity in vulnerabilities arising from the interplay of renewable resource availability, high load, and severe transmission line congestion. Our findings reveal a need for 61-105\% more firm, zero-emission capacity to ensure system reliability. Merely increasing wind and solar capacity is ineffective in improving reliability due to transmission congestion and spatiotemporal variations in vulnerabilities. This underscores the importance of considering spatiotemporal dynamics and operational constraints when making decisions regarding additional investments in renewable resources.