---
title: "Technical Comment on the DOE CWG report, Chapter 7: Changes in Sea Level"
date: 2025-09-29
author: 
  - name: Kopp, Robert E.
    orcid: 0000-0003-4016-9428
    url: https://www.bobkopp.net
  - name: Bassis, Jeremy
    orcid: 0000-0003-2946-7176
    url: https://jbassis.engin.umich.edu
  - name: Boesch, Don
    orcid: 0000-0002-8154-133X
    url: https://www.umces.edu/directory/donald-boesch/
  - name: Garner, Andra
    orcid: 0000-0002-4994-9271
    url: https://sites.google.com/site/andrajreed/
  - name: Sadai, Shaina
    orcid: 0000-0002-6723-6531
    url: https://www.scienceshaina.com
  - name: Vivek Srikrishnan
    orcid: 0000-0003-0049-3805
    url: https://viveks.me
  - name: Stearns, Leigh
    orcid: 0000-0001-7358-7015
    url: https://pennpolar.sas.upenn.edu
  - name: Tessa M. Hill
    orcid: 0000-0003-4159-9104
    url: https://hillbiogeochemistry.squarespace.com
categories:
    - climate impacts
    - sea-level rise
url_source: 
url_preprint: https://essopenarchive.org/doi/full/10.22541/essoar.175745244.4195
url_repo: 
pages: 247-267
year: 2025
doi: 10.22541/essoar.175745244.41950365/v2
---

## Abstract

Chapter 7 of the DOE CWG report addresses the topic of changes in sea level. As the chapter correctly notes, global-mean sea level (GMSL) has risen by about 8 inches since 1900, and this rise is “unambiguously associated with increasing temperatures” (p. 75). The chapter omits three critical assessments, discussed below:

* It conducts no systematic, statistical analysis to support its claim that there is "no obvious acceleration" of sea-level rise, either at individual tide gauges in the United States or in aggregate across U.S. tide gauges.
* It conducts no analysis to support its claim that sea level is rising at a lower rate than projected by the Intergovernmental Panel on Climate Change (IPCC)’s Sixth
Assessment Report (AR6).
* It contains no discussion of the current or future impacts of sea-level rise on the United States.

It also contains numerous statements that are not supported by a balanced assessment of the scientific literature, utilizes cherry picked data, and has pervasive issues with inadequate citation practices.


## Citation

```bibtex
@incollection{koppTechnicalCommentDOE2025,
  title = {Technical {{Comment}} on the {{DOE CWG}} Report, {{Chapter}} 7: {{Changes}} in {{Sea Level}}},
  booktitle = {Climate {{Experts}}' {{Review}} of the {{DOE Climate Working Group Report}}},
  author = {Kopp, Robert E and Bassis, Jeremy and Boesch, Don and Garner, Andra and Sadai, Shaina and Srikrishnan, Vivek and Stearns, Leigh and Hill, Tessa M},
  year = 2025,
  month = sep,
  pages = {247--267},
  doi = {10.22541/essoar.175745244.41950365/v2}
}
```