---
title: Environmental Systems Analysis
year: 2021
semester: Fall
coursenumber: BEE 4750/5750
---

- **Semester:** {{< meta semester >}} {{< meta year >}}
- **Course Number:** {{< meta coursenumber >}}

## Course Description

Environmental systems involve multiple interacting processes, uncertainties, and potentially conflicting objectives. These dynamics can complicate analyses which focus on a single component of the system, such as an individual pollution source, or a single outcome of interest. In this course, we will adopt a systems approach to environmental quality modeling and management, including applications in air and water pollution control and solid waste management. In particular, we will:

* define systems and their boundaries;
* simulate system dynamics using computer models;
* formulate and solve decision problems for systems management;
* analyze and assess risk;
* make decisions under uncertainty; and
* explore trade-offs across multiple objectives.

## More Information

- This course uses the [Julia programming language](https://julialang.org).
- This semester of BEE 4750/5750 is co-taught with [Prof. C. Lindsay Anderson](https://andersonenergylab-cornell.github.io/).