---
title: "Unlocking the benefits of transparent and reusable science for climate-risk management"
date: 2025-01-01
author: 
  - name: Adam Pollack
    orcid: 0000-0001-6642-0591
    url: https://abpoll.github.io/
  - name: Lisa Auermiller
    orcid: 0009-0002-3696-6491
    url: https://marine.rutgers.edu/team/lisa-auermuller/
  - name: Casey D. Burleyson
    orcid: 0000-0001-6218-9361
    url: http://caseyburleyson.com/
  - name: Jentry Campbell
    orcid: 0000-0001-8615-5094
    url: https://www.library.dartmouth.edu/directory/f0069hv
  - name: Madison Condon
    orcid: 0000-0001-8764-2249
    url: https://www.bu.edu/law/profile/madison-condon/
  - name: Courtney Cooper
    orcid: 0000-0002-4270-2778
    url: https://berry.edu/academics/fs/ccooper
  - name: Matteo Coronese
    orcid: 0000-0003-4134-1971
    url: https://matteocoronese.eu/
  - name: Sönke Dangendorf
    orcid: 0000-0002-3679-5234
    url: https://sse.tulane.edu/sonke-dangendorf
  - name: James Doss-Gollin
    orcid: 0000-0002-3428-2224
    url: https://dossgollin-lab.github.io/
  - name: Prabhat Hegde
  - name: Casey Helgeson
    orcid: 0000-0001-5333-9954
    url: https://caseyhelgeson.github.io/
  - name: Robert E. Kopp
    orcid: 0000-0003-4016-9428
    url: https://www.bobkopp.net
  - name: Jan Kwakkel
    orcid: 0000-0001-9447-2954
    url: https://www.tudelft.nl/en/staff/j.h.kwakkel/?cHash=292a774dd4cf8a0f554aef81e9f23bbb
  - name: Corey Lesk
    orcid: 0000-0003-0868-4040
    url: https://faculty-directory.dartmouth.edu/corey-s-lesk
  - name: Justin S. Mankin
    orcid: 0000-0003-2520-4555
    url: https://jsmankin.github.io
  - name: Robert E. Nicholas
    orcid: 0000-0003-2615-2574
    url: https://personal.ems.psu.edu/~ren10/
  - name: Jennie S. Rice
    orcid: 0000-0002-7833-9456
    url: https://www.pnnl.gov/people/jennie-rice
  - name: Samantha Roth
    orcid: 0000-0002-8867-4426
    url: https://samantha-roth.github.io
  - name: Vivek Srikrishnan
    orcid: 0000-0003-0049-3805
    url: https://viveks.me
  - name: Moira Scheeler
    orcid: 0009-0001-9675-7694
  - name: Nancy Tuana
    url: https://philosophy.la.psu.edu/people/nat3/
  - name: Chris R. Vernon
    orcid: 0000-0002-6045-7729
    url: https://energyenvironment.pnnl.gov/staff/staff_info.asp?staff_num=1834
  - name: Mengqi Zhao
    orcid: 0000-0001-5385-2758
    url: https://www.pnnl.gov/people/mengqi-zhao
  - name: Klaus Keller
    orcid: 0000-0002-5451-8687
    url: https://keller-lab.github.io/people.html
categories:
    - open science
url_source: 
url_preprint:
url_repo: https://github.com/abpoll/open/tree/submission
journ: "In Review"
doi: 10.31219/osf.io/29nhv
---

## Links

* [Code Repository](https://github.com/abpoll/open/tree/submission)

## Abstract

People around the world seek climate-risk information to guide their decisions. For instance, projections about future flood risk inform where households choose to live, how lenders manage credit risks, and which communities receive preference for federal funds. However, fundamental validation and verification challenges raise important concerns about the reliability of such projections. Accordingly,
many promote and standardize research transparency and reusability as foundations of reliable climate-risk knowledge because they enable rigorous scrutiny of methods, development of foundational tools, and design of evaluation standards. Despite prominent success stories in the field, we find a substantial gap between principles and practice: only four percent of the most-cited peer-reviewed climate-risk studies in recent years fully share their data and code despite this being a widely accepted minimum standard for transparency. We highlight low-cost measures that researchers can immediately implement to improve transparency and reusability. Yet we recognize that transformative progress requires substantial investments, cross-sector collaboration, and careful consideration of tradeoffs, data rights, and multiple perspectives on equity. We hope this perspective accelerates both immediate actions and longer-term conversations to improve the ability of science to effectively support timely, evidence-based, and sound climate-risk management.