---
title: "Impact of Hydropower Availability on Resource Adequacy of the
United States Western Interconnection"
date: 2025-01-01
author: 
  - name: Sai Veena Sunkara
    orcid: 0000-0002-5160-9663
  - name: Srihari Sundar
    orcid: 0000-0002-0556-3967
    url: https://research-hub.nrel.gov/en/persons/hari-sundar
  - name: Gord Stephen
    orcid: 0000-0002-1619-5151
    url: https://research-hub.nrel.gov/en/persons/gord-stephen
  - name: Stuart Cohen
    orcid: 0000-0001-8389-6516
    url: https://research-hub.nrel.gov/en/persons/stuart-cohen
  - name: Patrick Reed
    orcid: 0000-0002-7963-6102
    url: https://reed.cee.cornell.edu/
  - name: Vivek Srikrishnan
    orcid: 0000-0003-0049-3805
    url: https://viveks.me
categories:
    - climate risk management
    - hydropower
    - deep uncertainty
    - electric power systems
url_source: 
url_preprint: 
url_repo: 
journ: "Submitted"
year: 2025
---


## Abstract

Hydropower is a key energy source in the western interconnection of the United States, comprising about 25\% of the annual installed nameplate capacity in 2020. However, its generation is increasingly impacted by changing hydrological conditions, operational constraints, environmental factors, water availability, and aging dam infrastructure. Assessing hydropower availability and resource adequacy is valuable for shaping energy policies and infrastructure requirements. In this study we evaluate the sensitivity of resource adequacy in the Western Interconnection to the unavailability of hydropower plants, under a wide-ranging set of 16,834 hydropower loss scenarios derived from a combination of 14 major hydrologic regions. Although a complete loss of hydropower capacity in any region is unlikely, studying such scenarios helps in identifying hydrologic regions most critical for maintaining resource adequacy. So, we identify key hydrologic regions with disproportionately large adequacy impacts relative to their installed hydropower capacity and study compounding effects between regions using classification and regression trees. Even after controlling for total installed capacity, we find that hydropower resources in the Pacific Northwest contribute the most to interconnection-wide adequacy outcomes, with resources in Northern California and the Desert Southwest providing more moderate incremental contributions.