---
title: Climate Uncertainties
year: 2023
semester: Fall
coursenumber: ARCH 4101/7112
---

- **Semester:** {{< meta semester >}} {{< meta year >}}
- **Course Number:** {{< meta coursenumber >}}

## Course Description

Our journey will take us through a spectrum of climate-related themes,
from scrutinizing historical hazard events in modern socio-economic
contexts, to critically examining climate modeling and its unequal
impacts. We’ll delve deep into various climate risks—flooding, drought,
electric power system failures—all while focusing on the vulnerable and
marginalized communities that these events disproportionately impact.
The course’s pedagogical approach emphasizes the power of
collaboration. Students from diverse backgrounds will find a platform
where they can learn from and enrich each other’s understanding.
CALS students will have the opportunity to apply engineering and
ecological methods, while AAP students bring their spatial and design
expertise to the table. In parallel, we will also navigate the politics of
modeling, simulating, and visualizing climate realities, exploring how
these tools can be deployed to not just predict, but challenge and
disrupt the status quo.

Central to the course is the reinterpretation of ‘uncertainty.’ Rather
than viewing it as a hindrance, we consider it as a catalyst to challenge
conventional risk management paradigms, leading to innovative
interventions and the envisioning of diverse futures, identities, and
ways of being. The course leverages state-of-the-art tools, such as
uncertainty, hydrodynamic and agent-based modeling, digital twins,
and generative AI programming, offering students a multifaceted
approach to confronting real-world climate challenges. Beyond the
classroom, the course is enriched by a dedicated speaker series and
site visits, facilitated through generous funding. As part of the larger
The 2030 Project initiative, students will also have the opportunity to
showcase their work to a broader audience through publications,
exhibitions, and events, effectively bridging the gap between academia
and society, theory and practice. Our objective goes beyond developing
climate-aware professionals; we aim to cultivate proactive climate designers and engineers, ready to make a significant impact on our
collective futures.

**Key Learning Objectives**:

1. Analyze climate engineering challenges and design innovative
hydrologic solutions using spatial and engineering skills.
2. Foster interdisciplinary collaboration, integrating diverse design
and engineering principles to develop problem-solving
strategies.
3. Enhance interoperability across modeling and simulation tools.
4. Embrace uncertainty to envision just climate futures.


## More Information

- This design studio was co-taught with [Prof. Farzin Lofti-Jam](https://aap.cornell.edu/people/farzin-lotfi-jam).