---
title: "Explaining drivers of housing prices with nonlinear hedonic regressions"
date: 2025-01-01
author: 
  - name: Heng Wan
    orcid: 0000-0002-3747-6964
  - name: Brent Daniel
    orcid: 0000-0001-7398-6796
  - name: Vivek Srikrishnan
    orcid: 0000-0003-0049-3805
    url: https://viveks.me
  - name: Jim Yoon
    url: https://energyenvironment.pnnl.gov/staff/staff_info.asp?staff_num=3295
  - name: David Judi
    orcid: 0000-0003-0989-4525
    url: https://www.pnnl.gov/people/david-judi
  - name: Pranab Roy Chowdhury
    orcid: 0000-0002-7572-050X
  - name: Parin Bhaduri
    orcid: 0000-0002-4618-1121
categories:
    - machine learning
    - interpretable machine learning
    - housing markets
url_source: https://doi.org/10.1016/j.mlwa.2025.100707
url_preprint:
url_repo: 
journ: "Machine Learning with Applications"
issue: 21
page: 100707
year: 2025
---

## Abstract

Housing markets play a critical role in shaping the spatial and demographic evolution of urban areas. Simulating housing price dynamics can enhance projections of future urban development outcomes. However, traditional hedonic regressions for housing prices, which neglect nonlinear interactions among explanatory variables, often exhibit limited predictive performance. While machine learning (ML) methods can provide a more flexible representation of the relationships between predictors, they are often regarded as “black boxes” due to their complexity and lack of transparency. Interpretable ML techniques provide a promising route by combining the flexibility of ML methods with approaches to analyze the relationships between inputs and outputs. In this study, we employ interpretable ML to analyze the patterns driving the housing market in Baltimore, Maryland, USA. We train an Artificial Neural Network (ANN) to predict Baltimore housing prices based on structural characteristics (e.g., home size, number of stories) and locational attributes (e.g., distance to the city center). We then conduct sensitivity and Partial Dependence Plot (PDP) analyses to interpret the fitted ANN model. We find that the ML model achieves higher predictive accuracy and explains 16 % more of housing price variance than a traditional linear regression model. The interpretable ML model also reveals more nuanced and realistic nonlinear relationships between housing sales price and predictors as well as interactive effects underlying Baltimore home price dynamics. For instance, while the linear model indicates a steady housing price increase over time, our interpretable ML model detects a post-2008 decline, with smaller properties experiencing the sharpest drop.

## Citation

```bibtex
@ARTICLE{Wan2025-mg,
  title = {Explaining drivers of housing prices with nonlinear hedonic
  regressions},
  author = {Wan, Heng and Chowdhury, Pranab K Roy and Yoon, Jim and Bhaduri,
  Parin and Srikrishnan, Vivek and Judi, David and Daniel, Brent},
  journaltitle = {Mach. Learn. Appl.},
  volume = {21},
  pages = {100707},
  date = {2025},
  doi = {10.1016/j.mlwa.2025.100707}
}
```